---
name: PR One-Shot Test

on:
  pull_request_review:
    types: ["submitted"]

jobs:
  one-shot-test:
    # Only run when a pull request is approved by a contributor
    if: github.event.review.state == 'approved' && (github.event.review.author_association == 'COLLABORATOR' || github.event.review.author_association == 'MEMBER' || github.event.review.author_association == 'OWNER')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run one-shot test
        env:
          # OpenAI configuration
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'sk-test-placeholder-key-for-ci' }}
          OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL || '' }}
          OPENAI_MODEL_NAME: ${{ vars.OPENAI_MODEL_NAME || 'gpt-4o' }}
          OPENAI_TEMPERATURE: ${{ vars.OPENAI_TEMPERATURE || '0.7' }}
          # Server configuration
          PORT: ${{ vars.PORT || '8080' }}
          HOST: ${{ vars.HOST || '0.0.0.0' }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL || 'INFO' }}
          # Application configuration
          LOCAL_TOOLS_ENABLED: ${{ vars.LOCAL_TOOLS_ENABLED || 'true' }}
          MAX_TURNS: ${{ vars.MAX_TURNS || '25' }}
        run: |
          uv run main.py --one_shot=1